apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  namespace: lab
  labels:
    app: shoppingapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: shoppingapi-lab
        consul.hashicorp.com/service-tags: "\
          traefik.enable=true,\
          traefik.http.routers.shoppingapi-lab.entrypoints=websecure,\
          traefik.http.routers.shoppingapi-lab.rule=Host(`shoppingapi-lab.mypath.com`) && PathPrefix(`/`)"
    spec:
      containers:
        - name: shoppingapi
          image: mehmetozkaya/shoppingapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingapi-service
  namespace: lab
spec:
  type: ClusterIP
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
