apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-deployment
  namespace: lab
  labels:
    app: shoppingclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service: shoppingclient-lab
        consul.hashicorp.com/service-tags: "\
          traefik.enable=true,\
          traefik.http.routers.shoppingclient-lab.entrypoints=websecure,\
          traefik.http.routers.shoppingclient-lab.rule=Host(`shoppingclient-lab.mypath.com`) && PathPrefix(`/`)"
    spec:
      containers:
        - name: shoppingclient
          image: mehmetozkaya/shoppingclient:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                configMapKeyRef:
                  name: shoppingapi-configmap
                  key: shoppingapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-service
  namespace: lab
spec:
  type: ClusterIP
  selector:
    app: shoppingclient
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
